
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ahmn2
 */
public class CIT extends javax.swing.JFrame {

  /**
   * Creates new form CIT
   */
  public CIT() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    outputBox = new javax.swing.JTextArea();
    jButton2 = new javax.swing.JButton();
    searchButton = new javax.swing.JButton();
    jTextField1 = new javax.swing.JTextField();
    printCombo = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jComboBox2 = new javax.swing.JComboBox<>();
    jLabel4 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jTextField2 = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jButton4 = new javax.swing.JButton();
    jLabel6 = new javax.swing.JLabel();

    jLabel2.setText("jLabel2");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("CIT Demo");

    jButton1.setText("Read");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    outputBox.setColumns(20);
    outputBox.setRows(5);
    outputBox.setEnabled(false);
    jScrollPane1.setViewportView(outputBox);

    jButton2.setText("Print");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    searchButton.setText("Search");
    searchButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchButtonActionPerformed(evt);
      }
    });

    printCombo.setMaximumRowCount(3);
    printCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty", "Course" }));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel1.setForeground(java.awt.Color.red);
    jLabel1.setText("Loads data file");

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel3.setForeground(java.awt.Color.red);
    jLabel3.setText("Prints data");

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Faculty", "Course" }));

    jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel4.setForeground(java.awt.Color.red);
    jLabel4.setText("Searches the given query");

    jButton3.setText("Delete");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel5.setForeground(java.awt.Color.red);
    jLabel5.setText("Delete at a specific GPA");

    jButton4.setText("Avg GPA");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    jLabel6.setForeground(java.awt.Color.red);
    jLabel6.setText("Calculate avg GPA");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jTextField1)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(printCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel5)
              .addComponent(jLabel6))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jLabel1))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton2)
          .addComponent(jLabel3)
          .addComponent(printCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(searchButton)
        .addGap(15, 15, 15)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton4)
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    BufferedReader reader;
    try {
      reader = new BufferedReader(new FileReader("courses.in"));
      String line = reader.readLine();
      String[] data = line.split(",");
      while(line!= null)
      {
        test.courses.add(new Course(data[0], data[1], new Track(data[2].strip(), data[3].strip()), Integer.parseInt(data[4].strip())));
        line = reader.readLine();
      }
    } catch (IOException e) {
      outputBox.setText("File not found or file format error");
    }
    
    try {
      reader = new BufferedReader(new FileReader("faculty.in"));
      String line = reader.readLine();
      String[] data = line.split(",");
      while(line!= null)
      {
        test.facultyMembers.add(new Faculty(new Person(data[0].strip(), data[1].strip(), data[2].strip(), new Date(Integer.parseInt(data[3].strip()), Integer.parseInt(data[4].strip()), Integer.parseInt(data[5].strip())))));
        line = reader.readLine();
      }
    } catch (IOException e) {
      outputBox.setText("File not found or file format error");
    }
    
    try {
      reader = new BufferedReader(new FileReader("students.in"));
      String line = reader.readLine();
      String[] data = line.split(",");
      while(line!= null)
      {
        test.students.add(new Student(data[0].strip(),
                          new Person(data[1].strip(), data[2].strip(), data[3].strip(),
                          new Date(Integer.parseInt(data[4].strip()), Integer.parseInt(data[5].strip()), Integer.parseInt(data[6].strip()))),
                          new Address(Integer.parseInt(data[7].strip()), data[8].strip(), data[9].strip())));
        line = reader.readLine();
      }
    } catch (IOException e) {
      outputBox.setText("File not found or file format error");
    }
    outputBox.setText("File read successsfully!!!");
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int selection = printCombo.getSelectedIndex();
    switch(selection)
    {
      case 0:
      {
        String line = "";
        for(Student itr: test.getStudents())
        {
          line += itr.toString();
        }
        outputBox.setText(line);
        break;
      }
      case 1:
      {
        String line = "";
        for(Faculty itr: test.getFacultyMembers())
        {
          line += itr.toString();
        }
        outputBox.setText(line);
        break;
      }
      case 2:
      {
        String line = "";
        for(Course itr: test.getCourses())
        {
          line += itr.toString();
        }
        outputBox.setText(line);
        break;
      }
    }
  }//GEN-LAST:event_jButton2ActionPerformed

  private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
    int selection = printCombo.getSelectedIndex();
    switch(selection)
    {
      case 0:
      {
        for(Student itr: test.getStudents())
        {
          if(jTextField1.getText().equals(itr.getStudentID()))
          {
            outputBox.setText(itr.toString());
            return;
          }
        }
        outputBox.setText("Not found!!");
        break;
      }
      case 1:
      {
        for(Faculty itr: test.getFacultyMembers())
        {
          if(jTextField1.getText().equals(itr.getMember().getFname()))
          {
            outputBox.setText(itr.toString());
            return;
          }
        }
        outputBox.setText("Not found!!");
        break;
      }
      case 2:
      {
        for(Course itr: test.getCourses())
        {
          if(jTextField1.getText().equals(itr.getCourseID()))
          {
            outputBox.setText(itr.toString());
            return;
          }
        }
        outputBox.setText("Not found!!");
        break;
      }
    }
  }//GEN-LAST:event_searchButtonActionPerformed

  private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    outputBox.setText("Courses not set yet");
  }//GEN-LAST:event_jButton3ActionPerformed

  private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    outputBox.setText("Courses not set yet");
  }//GEN-LAST:event_jButton4ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(CIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(CIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(CIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(CIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new CIT().setVisible(true);
      }
    });
  }

  CITDemo test = new CITDemo();
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextArea outputBox;
  private javax.swing.JComboBox<String> printCombo;
  private javax.swing.JButton searchButton;
  // End of variables declaration//GEN-END:variables
}
